### ISSUE TITLE
Structures are extremely common

### ISSUE THREAD

**Issue by 1nforr** [tempestsbox/ttb#16]
Structures are extemely common. On my survival world, I found about 15 structures within 200 chunks of each other.

**Comment by dvitski** [comment]
You are extremely lucky. I barely ever get any spawns.

I envy you.

**Comment by dvitski** [comment]
https://cdn.discordapp.com/attachments/635633047743496202/745684582871072819/Screen_Shot_2020-08-19_at_11.44.02_AM.png

**Comment by MagmaSlime123** [comment]
So will this ever be fixed, might as well close it if not
